[tool.poetry]
name = "satellitevu"
version = "0.0.0"
description = "Client SDK for SatelliteVu's platform APIs"
authors = ["Christian Wygoda <christian.wygoda@satellitevu.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
appdirs = "^1.4.4"

[tool.poetry.group.dev.dependencies]
black = "^22.8.0"
flake8 = "^5.0.4"
isort = "^5.10.1"
nox = "^2022.8.7"
nox-poetry = "^1.0.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"
